### ISSUE TITLE
Refactor todo

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#143]
## WIP should be completed with time

- [ ] `host` parameter on MeiliSearch instance creation should not be called `hostURL` but host for consistency with the other packages.
- [ ] Make demo work
- [ ] Check URL format validity in `Config.validate` and check Host connection in `Config.url()` (or other name)
- [ ] Make tests independant 
- [ ] Generic usage consistency

**Comment by bidoubiwa** [comment]
Closed for prefered detailed issue
